"""empty message

Revision ID: cb35026c9754
Revises: d24bfcf2e7c8
Create Date: 2019-07-17 15:17:14.168075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table, column
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = 'cb35026c9754'
down_revision = 'd24bfcf2e7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE posts SET content="" WHERE content IS NULL')
    op.alter_column('posts', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    # ### end Alembic commands ###
